
spring:
  application:
    name: online-examination-platform
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/oep}
  jpa:
    hibernate:
      ddl-auto: validate

oep:
  exam:
    percentageCap: 80

jwt:
  secret-key: lwTBhcV4pH1SHfLWwMYwUSuByoqx9XWqdn3e3B4ikTqcJ888tK
server:
  port: 8081